name: parse2publish

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  main:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      # 签出当前仓库
      - name: Checkout code
        uses: actions/checkout@v4

      # 签出Website仓库
      - name: Checkout website repo
        uses: actions/checkout@v4
        with:
          repository: easybangumiorg/website
          path: website
          token: ${{ secrets.TOKEN }}
          ref: main

      # 安装依赖
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
            enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      # 运行解析器
      - name: Run parser
        run: uv run ebjer parse --from "extensions" --to "repository/v2"

      # 复制文件
      - name: Copy files
        run: |
          mkdir -p website/src/.vuepress/public/repository/v2/
          cp -r repository/v2/* website/src/.vuepress/public/repository/v2/
        
      # 创建提交
      - name: Create commit
        run: |
          pushd website
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add src/.vuepress/public/repository/v2/
          git commit -m "Update repository"

      # 提交更改
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          repository: easybangumiorg/website
          github_token: ${{ secrets.TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
